# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea6a1867e1b4eb2be9ab0a414ab0558b71cb088205e0861af9a2d38c610f81b8a1662e04a6545a3a8e16600006b643e7e6bb7b51b6f0427c122d6f0f63a45157

test:
  secret_key_base: 18336054b51ebeea7373420f37921804726a29f43bf8ff45ed033ed270db3a4885ab24b4e57612333a2157cebf37ae872490c6b8b0c28e052adefac8d1d38784

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
